### ISSUE TITLE
Turkish Translation For Better Chest

### ISSUE THREAD

**Issue by Vylesh** [ImJustMatt/ExpandedStorage#46]
Heya
I just wanted To say I'm making a Turkish Translation for mod. so For this i opened a ticket for it.

After finish i will send translation

**Comment by Vylesh** [comment]
Here is A trasnlation of mod

[Turkish.txt](https://github.com/ImJustMatt/StardewMods/files/8903144/Turkish.txt)

**Comment by Vylesh** [comment]
İ found some İssues like not translated areas... i gonna update translate tomorrow

**Comment by Vylesh** [comment]
Fixed Version
[Turkish - V1.1.txt](https://github.com/ImJustMatt/StardewMods/files/8903403/Turkish.-.V1.1.txt)
@ImJustMatt Sir plz use this version
İ hope its done now 😁

**Comment by LeFauxMatt** [comment]
Resolved as of today's release. Thank you for your contribution!
